### PR TITLE
refactor code

### PR DESCRIPTION
**Pull request by zoyatanweer**
changed the color of secondary button and corrected it in the places where it was used earlier.

### CODE REVIEW

**Review by zoef-yt — APPROVED** [review]
Small pr the code looks good. good to merge.

**Comment by Ranjeetk489** [comment]
Looks good from the perspective of readability, good to merge

**Review by abhishektanwar — APPROVED** [review]
Changes are fine.

**Review by dev-prabhat — APPROVED** [review]
color variable is meaningful, good to go

**Comment by zoyatanweer** [comment]
thanks for the review guys.

**Pull request merged**
