### PR TITLE
added readme images for readme file.

### PR DESCRIPTION
**Pull request by zoyatanweer**
added readme.md file and attached photos of components into it.

### CODE REVIEW

**Review by zoef-yt — APPROVED** [review]
Readme looks good. some images are not aligned properly in the readme. but everything looks great. good to merge.

**Review by Megha-Joshi — APPROVED** [review]
Looks good to me. Can be merged!

**Review by dev-prabhat — APPROVED** [review]
Readme file covers all the details which are required and adding image gives user a overall look of the components and understandable

**Comment by zoyatanweer** [comment]
thankyou for the review guys.

**Pull request merged**
